version: "3.9"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "authdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  migrate:
    image: golang:latest
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      go install github.com/pressly/goose/v3/cmd/goose@latest &&
      export PATH=$$PATH:/go/bin &&
      goose -dir migrations postgres 'postgres://postgres:postgres@database:5432/auth?sslmode=disable' up
      "
    depends_on:
      - database

  myapp:
    build: .
    depends_on:
      - database
      - migrate
    ports:
      - "8080:8080"


volumes:
  postgres_data:

